---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.19.36

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
